# Feature Improvement

Various feature improvement.

## Verbose Features

Dictionaries for explanations and improved feature names of the 2016 PUMF dataset.

In [2]:
import pandas as pd

In [3]:
fields = ['PPSORT', 'WEIGHT', 'ABOID', 'BFNMEMB', 'CFSTAT', 'Citizen', 'CMA',
       'DETH123', 'HHTYPE',
       'MarStH', 'PR', 'PRIHM', 'REGIND', 'Sex', 'SHELCO',
       'AGEGRP', 'ATTSCH', 'BedRm', 'CFInc', 'CFInc_AT', 'CfSize',
       'CIP2011', 'CIP2011_STEM_SUM', 'CONDO', 'DPGRSUM', 'DTYPE',
       'EFDecile', 'EfDIMBM', 'EFInc', 'EFInc_AT', 'EfSize', 'ETHDER',
       'GENSTAT', 'HCORENEED_IND', 'HDGREE', 'HHInc', 'HHInc_AT',
       'HHMRKINC', 'HHSIZE', 'HLANO', 'IMMCAT5', 'IMMSTAT',
       'LFACT', 'LICO', 'LICO_AT', 'LOC_ST_RES', 'LoLIMA', 'LoLIMB',
       'LoMBM', 'LSTWRK', 'MOB1', 'Mob5', 'MrkInc',
       'MTNNO', 'NOS', 'PKID0_1', 'PKID15_24', 'PKID2_5', 'PKID25',
       'PKID6_14', 'PKIDS', 'POB', 'POBF', 'POBM', 'PR1', 'PR5',
       'PresMortG', 'REPAIR', 'ROOMS', 'SSGRAD', 'Tenur', 'TotInc',
       'TotInc_AT', 'VALUE', 'VisMin', 'WRKACT']

In [4]:
field_name_data = pd.read_csv('Data_Mining_Names.csv')

field_name_data

,Mapping_Needed,Data_Type,Meaning,Definitive_Name,dataset_2016
0,NaN,Discrete,Unique record (row) identifier,Row_ID_PPsort,PPSORT
1,NaN,Continuous,No. of individuals represented by this row,Row_Weight,WEIGHT
2,Possibly,Categorical,Detailed aboriginal identity,Aboriginal_Identity,ABOID
3,NaN,"Binary (0,1)",Membership in a First Nation or band,FN_Band_Membership,BFNMEMB
4,Possibly,Categorical,"Living arrangement (e.g. married, single)",Household_Living_Arrangements,CFSTAT
...,...,...,...,...,...
71,NaN,Continuous,Total personal income from recurring sources,Total_Personal_Recurring_Income,TotInc
72,NaN,Continuous,Total personal income from recurring sources a...,Total_Personal_Recurring_Income_After_Tax,TotInc_AT
73,NaN,Continuous,Household property value (including land),Property_Value,VALUE
74,Likely,Categorical,Visible minority group,Visible_Minority_Group,VisMin
75,NaN,Categorical,Work activity in 2015 (e.g. worked 1-13 weeks),Work_Activity_Status_in_2015,WRKACT

In [9]:
data_types = field_name_data['Data_Type']
meanings = field_name_data['Meaning']

descriptions = []

for types, meaning in zip(data_types, meanings):
    descriptions.append(types + ': ' + meaning)

description_dict = dict(zip(field_name_data['dataset_2016'], descriptions))

description_dict

{'PPSORT': 'Discrete: Unique record (row) identifier',
 'WEIGHT': 'Continuous: No. of individuals represented by this row',
 'ABOID': 'Categorical: Detailed aboriginal identity',
 'BFNMEMB': 'Binary (0,1): Membership in a First Nation or band',
 'CFSTAT': 'Categorical: Living arrangement (e.g. married, single)',
 'Citizen': 'Categorical: Canadian citizenship status',
 'CMA': 'Categorical: Area of current residence',
 'DETH123': 'Binary (1,2): Single or multiple ethnic origin',
 'HHTYPE': 'Categorical: Household type (e.g. multiple family)',
 'MarStH': 'Categorical: Marital status',
 'PR': 'Categorical: Province or territory of current residence',
 'PRIHM': 'Binary (0,1): Person is primary household maintainer',
 'REGIND': 'Binary (0,1): Registered or treaty First Nation status',
 'Sex': 'Binary (1,2): Male or female sex',
 'SHELCO': 'Continuous: Average monthly cost of shelter',
 'AGEGRP': 'Categorical: Age bracket',
 'ATTSCH': 'Categorical: Highest education level ever attended',
 'BedRm': 'Discrete (0-5+): Number of bedrooms in household',
 'CFInc': 'Categorical: Census family income bracket',
 'CFInc_AT': 'Categorical: Census family income bracket after tax',
 'CfSize': 'Discrete (1-7+): Number of persons in census family',
 'CIP2011': 'Categorical: Postsecondary field of study',
 'CIP2011_STEM_SUM': 'Categorical: Postsecondary field (STEM & BHASE)',
 'CONDO': 'Binary (0,1): Resides in a condominium development',
 'DPGRSUM': 'Categorical: Population (cultural) group',
 'DTYPE': 'Categorical: Dwelling structure type (e.g. apartment)',
 'EFDecile': 'Discrete (1-10): Total family income decile after tax',
 'EfDIMBM': 'Categorical: Economic family disposable income',
 'EFInc': 'Categorical: Economic family income bracket',
 'EFInc_AT': 'Categorical: Economic family income bracket after tax',
 'EfSize': 'Discrete (1-7+): Number of persons in economic family',
 'ETHDER': 'Categorical: Ethnic origin',
 'GENSTAT': 'Categorical: Generation status (e.g. 1st gen. immigrant)',
 'HCORENEED_IND': 'Binary (0,100): Whether household is inadequate',
 'HDGREE': 'Categorical: Highest certificate, diploma, or degree',
 'HHInc': 'Categorical: Household income bracket',
 'HHInc_AT': 'Categorical: Household income bracket after tax',
 'HHMRKINC': 'Categorical: Household market income bracket',
 'HHSIZE': 'Discrete (1-7+): Number of persons in household',
 'HLANO': 'Categorical: Language most spoken at home',
 'IMMCAT5': 'Categorical: Immigration category (detailed categories)',
 'IMMSTAT': 'Categorical: Immigration status (e.g. immigrant vs non)',
 'LFACT': 'Categorical: Labour force status (e.g. unemployed)',
 'LICO': 'Binary (1,2): Non-low or low income cut-off economic family',
 'LICO_AT': 'Binary (1,2): Non-low or low income cut-off economic family after tax',
 'LOC_ST_RES': 'Categorical: Highest education location vs residence',
 'LoLIMA': 'Binary (1,2): Non-low or low income measure person after tax',
 'LoLIMB': 'Binary (1,2): Non-low or low income measure person before tax',
 'LoMBM': 'Binary (1,2): Non-low or low income Market Based Measure',
 'LSTWRK': 'Categorical: When last worked for pay or in self-employment',
 'MOB1': 'Categorical: 1 year mobility status (e.g. interprovincial migrant)',
 'Mob5': 'Categorical: 5 year mobility status (e.g. interprovincial migrant)',
 'MrkInc': 'Discrete: Sum personal income from all source',
 'MTNNO': 'Categorical: Mother tongue (first language spoken)',
 'NOS': 'Binary (0,1): Housing accomodations are suitable',
 'PKID0_1': 'Binary (0,1): Presence of children in household aged 0-1',
 'PKID15_24': 'Binary (0,1): Presence of children in household aged 15-24',
 'PKID2_5': 'Binary (0,1): Presence of children in household aged 2-5',
 'PKID25': 'Binary (0,1): Presence of children in household aged 25+',
 'PKID6_14': 'Binary (0,1): Presence of children in household aged 6_14',
 'PKIDS': 'Binary (0,1): Presence of children in any household',
 'POB': 'Categorical: Place of birth',
 'POBF': "Categorical: Father's place of birth",
 'POBM': "Categorical: Mother's place of birth",
 'PR1': 'Categorical: Province or territory of residence 1 year ago',
 'PR5': 'Categorical: Province or territory of residence 5 years ago',
 'PresMortG': 'Binary (0,1): Presence of mortgage',
 'REPAIR': 'Categorical: Need of dwelling repairs',
 'ROOMS': 'Discrete (0-11+): Number of rooms in household',
 'SSGRAD': 'Categorical: Secondary school diploma or certificate',
 'Tenur': 'Binary (1,2): Household owns residence or rents/lives in band housing',
 'TotInc': 'Continuous: Total personal income from recurring sources',
 'TotInc_AT': 'Continuous: Total personal income from recurring sources after tax',
 'VALUE': 'Continuous: Household property value (including land)',
 'VisMin': 'Categorical: Visible minority group',
 'WRKACT': 'Categorical: Work activity in 2015 (e.g. worked 1-13 weeks)'}

In [10]:
name_dict = dict(zip(field_name_data['dataset_2016'], field_name_data['Definitive_Name']))

name_dict

{'PPSORT': 'Row_ID_PPsort',
 'WEIGHT': 'Row_Weight',
 'ABOID': 'Aboriginal_Identity',
 'BFNMEMB': 'FN_Band_Membership',
 'CFSTAT': 'Household_Living_Arrangements',
 'Citizen': 'Canadian_Citizenship',
 'CMA': 'Metro_Area_Current_Residence',
 'DETH123': 'Single_or_Multiple_Ethnic_Origin',
 'HHTYPE': 'Household_Family_Status',
 'MarStH': 'Marital_Status',
 'PR': 'Province_Current_Residence',
 'PRIHM': 'Is_Primary_Household_Maintainer',
 'REGIND': 'Registered_Treaty_Status',
 'Sex': 'Sex',
 'SHELCO': 'Shelter_Cost',
 'AGEGRP': 'Age_Bracket',
 'ATTSCH': 'Education_Level_Attended',
 'BedRm': 'Household_Bedroom_Count',
 'CFInc': 'Census_Family_Income_Bracket',
 'CFInc_AT': 'Census_Family_Income_After_Tax',
 'CfSize': 'Census_Family_Size',
 'CIP2011': 'Postsecondary_Field_of_Study',
 'CIP2011_STEM_SUM': 'Postsecondary_Field_STEM_or_BHASE',
 'CONDO': 'Condominium_Membership',
 'DPGRSUM': 'Population_Group',
 'DTYPE': 'Dwelling_Structure_Type',
 'EFDecile': 'Economic_Family_Income_Decile_After_Tax',
 'EfDIMBM': 'Economic_Family_Disposable_Income',
 'EFInc': 'Economic_Family_Income_Bracket',
 'EFInc_AT': 'Economic_Family_Income_Bracket_After_Tax',
 'EfSize': 'Economic_Family_Size',
 'ETHDER': 'Ethnic_Origin',
 'GENSTAT': 'Immigrant_Generation_Status',
 'HCORENEED_IND': 'Household_In_Core_Need',
 'HDGREE': 'Highest_Certificate_Degree',
 'HHInc': 'Household_Income_Bracket',
 'HHInc_AT': 'Household_Income_Bracket_After_Tax',
 'HHMRKINC': 'Household_Market_Income_Bracket',
 'HHSIZE': 'Household_Size',
 'HLANO': 'Home_Language',
 'IMMCAT5': 'Immigration_Detailed_Category',
 'IMMSTAT': 'Immigrant_Status',
 'LFACT': 'Labour_Force_Status',
 'LICO': 'Ec_Family_Low_Income_Cutoff',
 'LICO_AT': 'Ec_Family_Low_Income_Cutoff_After_Tax',
 'LOC_ST_RES': 'Highest_Education_Location_vs_Residence',
 'LoLIMA': 'Person_Low_Income_Measure_After_Tax',
 'LoLIMB': 'Person_Low_Income_Measure_Before_Tax',
 'LoMBM': 'Person_Low_Income_Market_Based_Measure',
 'LSTWRK': 'When_Last_Worked_For_Income',
 'MOB1': 'Residence_Mobility_Status_1_Year_Ago',
 'Mob5': 'Residence_Mobility_Status_5_Year_Ago',
 'MrkInc': 'Sum_Personal_Income_All',
 'MTNNO': 'Mother_Tongue',
 'NOS': 'Housing_Suitability',
 'PKID0_1': 'Has_Children_In_Household_Age_0_1',
 'PKID15_24': 'Has_Children_In_Household_Age_15_24',
 'PKID2_5': 'Has_Children_In_Household_Age_2_5',
 'PKID25': 'Has_Children_In_Household_Age_25_Plus',
 'PKID6_14': 'Has_Children_In_Household_Age_6_14',
 'PKIDS': 'Has_Children_In_Household',
 'POB': 'Place_of_Birth',
 'POBF': 'Father_Place_of_Birth',
 'POBM': 'Mother_Place_of_Birth',
 'PR1': 'Province_Residence_1_Year_Ago',
 'PR5': 'Province_Residence_5_Years_Ago',
 'PresMortG': 'Has_Mortgage',
 'REPAIR': 'Dwelling_Repair_Need_Status',
 'ROOMS': 'Household_Room_Count',
 'SSGRAD': 'Secondary_Degree_Certificate',
 'Tenur': 'Household_Ownership_or_Not',
 'TotInc': 'Total_Personal_Recurring_Income',
 'TotInc_AT': 'Total_Personal_Recurring_Income_After_Tax',
 'VALUE': 'Property_Value',
 'VisMin': 'Visible_Minority_Group',
 'WRKACT': 'Work_Activity_Status_in_2015'}

### Pipeline: Verbose Features

In [27]:
import pandas as pd

def get_verbose_feature_dicts():
    """Return verbose field name dict and verbose field description dict."""
    
    field_name_data = pd.read_csv('Data_Mining_Names.csv')
    
    data_types = field_name_data['Data_Type']
    meanings = field_name_data['Meaning']

    descriptions = []

    for types, meaning in zip(data_types, meanings):
        descriptions.append(types + ': ' + meaning)

    description_dict = dict(zip(field_name_data['dataset_2016'], descriptions))
    name_dict = dict(zip(field_name_data['dataset_2016'], field_name_data['Definitive_Name']))
    
    return description_dict, name_dict


get_verbose_feature_dicts()

({'PPSORT': 'Discrete: Unique record (row) identifier',
  'WEIGHT': 'Continuous: No. of individuals represented by this row',
  'ABOID': 'Categorical: Detailed aboriginal identity',
  'BFNMEMB': 'Binary (0,1): Membership in a First Nation or band',
  'CFSTAT': 'Categorical: Living arrangement (e.g. married, single)',
  'Citizen': 'Categorical: Canadian citizenship status',
  'CMA': 'Categorical: Area of current residence',
  'DETH123': 'Binary (1,2): Single or multiple ethnic origin',
  'HHTYPE': 'Categorical: Household type (e.g. multiple family)',
  'MarStH': 'Categorical: Marital status',
  'PR': 'Categorical: Province or territory of current residence',
  'PRIHM': 'Binary (0,1): Person is primary household maintainer',
  'REGIND': 'Binary (0,1): Registered or treaty First Nation status',
  'Sex': 'Binary (1,2): Male or female sex',
  'SHELCO': 'Continuous: Average monthly cost of shelter',
  'AGEGRP': 'Categorical: Age bracket',
  'ATTSCH': 'Categorical: Highest education level ever attended',
  'BedRm': 'Discrete (0-5+): Number of bedrooms in household',
  'CFInc': 'Categorical: Census family income bracket',
  'CFInc_AT': 'Categorical: Census family income bracket after tax',
  'CfSize': 'Discrete (1-7+): Number of persons in census family',
  'CIP2011': 'Categorical: Postsecondary field of study',
  'CIP2011_STEM_SUM': 'Categorical: Postsecondary field (STEM & BHASE)',
  'CONDO': 'Binary (0,1): Resides in a condominium development',
  'DPGRSUM': 'Categorical: Population (cultural) group',
  'DTYPE': 'Categorical: Dwelling structure type (e.g. apartment)',
  'EFDecile': 'Discrete (1-10): Total family income decile after tax',
  'EfDIMBM': 'Categorical: Economic family disposable income',
  'EFInc': 'Categorical: Economic family income bracket',
  'EFInc_AT': 'Categorical: Economic family income bracket after tax',
  'EfSize': 'Discrete (1-7+): Number of persons in economic family',
  'ETHDER': 'Categorical: Ethnic origin',
  'GENSTAT': 'Categorical: Generation status (e.g. 1st gen. immigrant)',
  'HCORENEED_IND': 'Binary (0,100): Whether household is inadequate',
  'HDGREE': 'Categorical: Highest certificate, diploma, or degree',
  'HHInc': 'Categorical: Household income bracket',
  'HHInc_AT': 'Categorical: Household income bracket after tax',
  'HHMRKINC': 'Categorical: Household market income bracket',
  'HHSIZE': 'Discrete (1-7+): Number of persons in household',
  'HLANO': 'Categorical: Language most spoken at home',
  'IMMCAT5': 'Categorical: Immigration category (detailed categories)',
  'IMMSTAT': 'Categorical: Immigration status (e.g. immigrant vs non)',
  'LFACT': 'Categorical: Labour force status (e.g. unemployed)',
  'LICO': 'Binary (1,2): Non-low or low income cut-off economic family',
  'LICO_AT': 'Binary (1,2): Non-low or low income cut-off economic family after tax',
  'LOC_ST_RES': 'Categorical: Highest education location vs residence',
  'LoLIMA': 'Binary (1,2): Non-low or low income measure person after tax',
  'LoLIMB': 'Binary (1,2): Non-low or low income measure person before tax',
  'LoMBM': 'Binary (1,2): Non-low or low income Market Based Measure',
  'LSTWRK': 'Categorical: When last worked for pay or in self-employment',
  'MOB1': 'Categorical: 1 year mobility status (e.g. interprovincial migrant)',
  'Mob5': 'Categorical: 5 year mobility status (e.g. interprovincial migrant)',
  'MrkInc': 'Discrete: Sum personal income from all source',
  'MTNNO': 'Categorical: Mother tongue (first language spoken)',
  'NOS': 'Binary (0,1): Housing accomodations are suitable',
  'PKID0_1': 'Binary (0,1): Presence of children in household aged 0-1',
  'PKID15_24': 'Binary (0,1): Presence of children in household aged 15-24',
  'PKID2_5': 'Binary (0,1): Presence of children in household aged 2-5',
  'PKID25': 'Binary (0,1): Presence of children in household aged 25+',
  'PKID6_14': 'Binary (0,1): Presence of children in household aged 6_14',
  'PKIDS': 'Binary (0,1): Presence of children in any household',
  'POB': 'Categorical: Place of birth',
  'POBF': "Categorical: Father's place of birth",
  'POBM': "Categorical: Mother's place of birth",
  'PR1': 'Categorical: Province or territory of residence 1 year ago',
  'PR5': 'Categorical: Province or territory of residence 5 years ago',
  'PresMortG': 'Binary (0,1): Presence of mortgage',
  'REPAIR': 'Categorical: Need of dwelling repairs',
  'ROOMS': 'Discrete (0-11+): Number of rooms in household',
  'SSGRAD': 'Categorical: Secondary school diploma or certificate',
  'Tenur': 'Binary (1,2): Household owns residence or rents/lives in band housing',
  'TotInc': 'Continuous: Total personal income from recurring sources',
  'TotInc_AT': 'Continuous: Total personal income from recurring sources after tax',
  'VALUE': 'Continuous: Household property value (including land)',
  'VisMin': 'Categorical: Visible minority group',
  'WRKACT': 'Categorical: Work activity in 2015 (e.g. worked 1-13 weeks)'},
 {'PPSORT': 'Row_ID_PPsort',
  'WEIGHT': 'Row_Weight',
  'ABOID': 'Aboriginal_Identity',
  'BFNMEMB': 'FN_Band_Membership',
  'CFSTAT': 'Household_Living_Arrangements',
  'Citizen': 'Canadian_Citizenship',
  'CMA': 'Metro_Area_Current_Residence',
  'DETH123': 'Single_or_Multiple_Ethnic_Origin',
  'HHTYPE': 'Household_Family_Status',
  'MarStH': 'Marital_Status',
  'PR': 'Province_Current_Residence',
  'PRIHM': 'Is_Primary_Household_Maintainer',
  'REGIND': 'Registered_Treaty_Status',
  'Sex': 'Sex',
  'SHELCO': 'Shelter_Cost',
  'AGEGRP': 'Age_Bracket',
  'ATTSCH': 'Education_Level_Attended',
  'BedRm': 'Household_Bedroom_Count',
  'CFInc': 'Census_Family_Income_Bracket',
  'CFInc_AT': 'Census_Family_Income_After_Tax',
  'CfSize': 'Census_Family_Size',
  'CIP2011': 'Postsecondary_Field_of_Study',
  'CIP2011_STEM_SUM': 'Postsecondary_Field_STEM_or_BHASE',
  'CONDO': 'Condominium_Membership',
  'DPGRSUM': 'Population_Group',
  'DTYPE': 'Dwelling_Structure_Type',
  'EFDecile': 'Economic_Family_Income_Decile_After_Tax',
  'EfDIMBM': 'Economic_Family_Disposable_Income',
  'EFInc': 'Economic_Family_Income_Bracket',
  'EFInc_AT': 'Economic_Family_Income_Bracket_After_Tax',
  'EfSize': 'Economic_Family_Size',
  'ETHDER': 'Ethnic_Origin',
  'GENSTAT': 'Immigrant_Generation_Status',
  'HCORENEED_IND': 'Household_In_Core_Need',
  'HDGREE': 'Highest_Certificate_Degree',
  'HHInc': 'Household_Income_Bracket',
  'HHInc_AT': 'Household_Income_Bracket_After_Tax',
  'HHMRKINC': 'Household_Market_Income_Bracket',
  'HHSIZE': 'Household_Size',
  'HLANO': 'Home_Language',
  'IMMCAT5': 'Immigration_Detailed_Category',
  'IMMSTAT': 'Immigrant_Status',
  'LFACT': 'Labour_Force_Status',
  'LICO': 'Ec_Family_Low_Income_Cutoff',
  'LICO_AT': 'Ec_Family_Low_Income_Cutoff_After_Tax',
  'LOC_ST_RES': 'Highest_Education_Location_vs_Residence',
  'LoLIMA': 'Person_Low_Income_Measure_After_Tax',
  'LoLIMB': 'Person_Low_Income_Measure_Before_Tax',
  'LoMBM': 'Person_Low_Income_Market_Based_Measure',
  'LSTWRK': 'When_Last_Worked_For_Income',
  'MOB1': 'Residence_Mobility_Status_1_Year_Ago',
  'Mob5': 'Residence_Mobility_Status_5_Year_Ago',
  'MrkInc': 'Sum_Personal_Income_All',
  'MTNNO': 'Mother_Tongue',
  'NOS': 'Housing_Suitability',
  'PKID0_1': 'Has_Children_In_Household_Age_0_1',
  'PKID15_24': 'Has_Children_In_Household_Age_15_24',
  'PKID2_5': 'Has_Children_In_Household_Age_2_5',
  'PKID25': 'Has_Children_In_Household_Age_25_Plus',
  'PKID6_14': 'Has_Children_In_Household_Age_6_14',
  'PKIDS': 'Has_Children_In_Household',
  'POB': 'Place_of_Birth',
  'POBF': 'Father_Place_of_Birth',
  'POBM': 'Mother_Place_of_Birth',
  'PR1': 'Province_Residence_1_Year_Ago',
  'PR5': 'Province_Residence_5_Years_Ago',
  'PresMortG': 'Has_Mortgage',
  'REPAIR': 'Dwelling_Repair_Need_Status',
  'ROOMS': 'Household_Room_Count',
  'SSGRAD': 'Secondary_Degree_Certificate',
  'Tenur': 'Household_Ownership_or_Not',
  'TotInc': 'Total_Personal_Recurring_Income',
  'TotInc_AT': 'Total_Personal_Recurring_Income_After_Tax',
  'VALUE': 'Property_Value',
  'VisMin': 'Visible_Minority_Group',
  'WRKACT': 'Work_Activity_Status_in_2015'})

---

## Discretization

Converting continuous and wide-domain discrete values into categorical deciles.

In [2]:
import pandas as pd

field_name_data = pd.read_csv('Data_Mining_Names.csv')

data_types = field_name_data['Data_Type']
dataset_names = field_name_data['dataset_2016']

to_categorize = []

for types, names in zip(data_types, dataset_names):
    if types in ('Discrete', 'Continuous') and names not in ('PPSORT', 'WEIGHT'):
        # Omitting row identifier and row weight (should not be used)
        to_categorize.append(names)

to_categorize

['SHELCO', 'MrkInc', 'TotInc', 'TotInc_AT', 'VALUE']

In [3]:
dataset_2016 = pd.read_csv('pumf-98M0001-E-2016-individuals_F1.csv')

dataset_2016['SHELCO']

0         2500
1         2400
2         2500
3         1300
4          700
5         1100
6         1000
7          900
8          900
9         2100
10        1800
11        1700
12         700
13        2700
14        2553
15        1900
16        1800
17         500
18         800
19        2200
20        2400
21        2700
22        1100
23        2100
24         800
25        1300
26        4156
27        4156
28        2658
29        2400
          ...
930391    1500
930392    1600
930393    1500
930394    1500
930395    1500
930396     800
930397     500
930398     700
930399    1400
930400    1200
930401    1300
930402    1200
930403     800
930404     600
930405    1900
930406    1800
930407    1500
930408    1300
930409    1300
930410    1200
930411    1400
930412    1300
930413    1500
930414    1400
930415    1400
930416     600
930417    1900
930418    3294
930419    1500
930420    1400
Name: SHELCO, Length: 930421, dtype: int64

In [4]:
pd.qcut(dataset_2016['SHELCO'], 10, False)

0         8
1         8
2         8
3         4
4         1
5         4
6         3
7         2
8         2
9         8
10        7
11        6
12        1
13        9
14        8
15        7
16        7
17        0
18        2
19        8
20        8
21        9
22        4
23        8
24        2
25        4
26        9
27        9
28        9
29        8
         ..
930391    5
930392    6
930393    5
930394    5
930395    5
930396    2
930397    0
930398    1
930399    5
930400    4
930401    4
930402    4
930403    2
930404    1
930405    7
930406    7
930407    5
930408    4
930409    4
930410    4
930411    5
930412    4
930413    5
930414    5
930415    5
930416    1
930417    7
930418    9
930419    5
930420    5
Name: SHELCO, Length: 930421, dtype: int64

### Pipeline: Discretization

In [5]:
import pandas as pd

def discretify(dataset, quantiles=10, target_fields=('SHELCO', 'MrkInc', 'TotInc', 'TotInc_AT', 'VALUE'),
               invalid_quantile = 88):
    """Convert target fields in dataset to quantile categories."""
    
    invalid_values = {
        'SHELCO': (),
        'MrkInc': (88888888, 99999999),
        'TotInc': (88888888, 99999999),
        'TotInc_AT': (88888888, 99999999),
        'VALUE': (88888888, 99999999)
    }
    
    dataset_copy = dataset.copy()

    for continuous in target_fields:
        if continuous in dataset_copy:
            print(continuous)
            values = []
            quantile_values = pd.qcut(dataset_copy[continuous].rank(method='first'), quantiles, False)

            for value, quantile in zip(dataset_copy[continuous], quantile_values):
                if value in invalid_values[continuous]:
                    values.append(invalid_quantile)
                else:
                    values.append(quantile)

            dataset_copy[continuous] = values
    
    return dataset_copy


discretify(dataset_2016)

SHELCO
MrkInc
TotInc
TotInc_AT
VALUE

,PPSORT,WEIGHT,WT1,WT2,WT3,WT4,WT5,WT6,WT7,WT8,...,Subsidy,Tenur,TotInc,TotInc_AT,VALUE,VisMin,Wages,WKSWRK,WRKACT,YRIMM
0,453141,37.037277,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9,1,7,7,4,13,95000,6,11,9999
1,923226,37.037277,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9,1,88,88,4,13,99999999,9,99,9999
2,385097,37.037277,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9,1,88,88,4,13,99999999,9,99,9999
3,732612,37.037277,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,592.596438,...,9,1,4,5,6,13,19000,6,11,9999
4,143665,37.120914,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9,1,3,3,0,13,29000,5,9,9999
5,459269,37.037277,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,592.596438,...,9,1,6,6,6,13,99999999,9,1,9999
6,632419,37.037277,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,592.596438,...,9,1,5,5,6,13,99999999,9,1,9999
7,284347,37.019784,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9,1,4,4,2,13,99999999,9,1,9999
8,52611,37.041550,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,2,5,5,88,13,52000,6,11,9999
9,36927,37.037277,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9,1,3,3,5,13,27000,4,7,9999
10,268123,37.037277,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,2,4,3,88,13,57000,6,11,9999
11,140411,37.037277,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,2,88,88,88,13,99999999,9,99,9999
12,361694,37.039118,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,2,1,1,88,13,99999999,9,1,9999
13,700087,37.037277,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9,1,6,6,5,13,70000,6,11,9999
14,488335,37.039118,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9,1,5,6,3,13,55000,6,11,9999
15,491822,37.039118,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9,1,88,88,3,13,99999999,9,99,9999
16,871649,37.037277,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9,1,0,0,2,13,99999999,6,11,9999
17,591795,37.037277,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9,1,2,2,2,13,24000,6,11,9999
18,584156,37.042280,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,2,4,4,88,13,11000,1,4,9999
19,753984,37.042280,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9,1,7,7,5,12,120000,6,11,7
20,143935,37.042280,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9,1,88,88,5,12,99999999,9,99,9999
21,838385,37.037277,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,592.596438,...,9,1,0,0,5,2,99999999,9,1,9999
22,379910,37.039118,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9,1,3,3,0,13,1000,9,1,9999
23,553949,37.037277,592.596438,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9,1,88,88,6,13,99999999,9,1,9999
24,558160,37.012589,0.000000,0.000000,0.000000,0.000000,0.000000,592.201426,0.000000,0.000000,...,0,2,5,4,88,13,47000,6,11,9999
25,476911,37.041550,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9,1,5,5,2,13,60000,5,9,9999
26,360026,37.042280,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9,1,88,88,6,1,99999999,9,99,9999
27,359002,37.042280,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9,1,3,3,6,13,26000,6,11,9999
28,816278,37.041550,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9,1,88,88,6,12,99999999,9,99,9999
29,810849,37.042280,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9,1,88,88,6,13,99999999,6,12,9999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
930391,460212,37.040742,0.000000,592.651871,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9,1,6,6,1,13,67000,6,11,9999
930392,88813,37.040742,0.000000,592.651871,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9,1,88,88,1,13,88888888,6,11,9999
930393,756172,37.041550,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9,1,5,5,0,13,50000,6,11,9999
930394,916873,37.041550,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9,1,88,88,0,13,99999999,9,99,9999
930395,413902,37.041550,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9,1,88,88,0,13,99999999,9,99,9999
930396,829443,37.041550,0.000000,0.000000,0.000000,0.000000,592.664803,0.000000,0.000000,0.000000,...,0,2,88,88,88,13,99999999,9,99,9999
930397,491461,37.037277,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,592.596438,0.000000,...,9,1,88,88,5,13,99999999,9,99,9999
930398,6746,37.037277,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,592.596438,...,9,1,7,7,6,13,99999999,9,1,4
930399,306904,37.051222,0.000000,0.000000,0.000000,592.819547,0.000000,0.000000,0.000000,0.000000,...,9,1,7,7,3,13,130000,6,11,9999
930400,271742,37.051222,0.000000,0.000000,0.000000,592.819547,0.000000,0.000000,0.000000,0.000000,...,9,1,88,88,3,13,99999999,9,99,9999
930401,132951,37.051222,0.000000,0.000000,0.000000,592.819547,0.000000,0.000000,0.000000,0.000000,...,9,1,88,88,3,13,99999999,9,99,9999
930402,56338,37.051222,0.000000,0.000000,0.000000,592.819547,0.000000,0.000000,0.000000,0.000000,...,9,1,88,88,3,13,99999999,9,99,9999
930403,39799,37.019784,0.000000,0.000000,0.000000,0.000000,592.316546,0.000000,0.000000,0.000000,...,1,2,0,0,88,13,99999999,9,1,9999
930404,627018,37.032779,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,592.524462,...,0,2,5,5,88,13,17000,5,10,9999
930405,482378,37.019784,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,2,5,6,88,13,99999999,5,9,9999
930406,704428,37.037277,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9,1,88,88,4,13,99999999,9,99,9999
930407,319614,37.041550,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9,1,6,5,3,4,64000,6,11,2000
930408,12864,37.037277,0.000000,0.000000,0.000000,0.000000,0.000000,592.596438,0.000000,0.000000,...,0,2,4,4,88,13,28000,5,9,9999
930409,695773,37.032779,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9,1,5,5,1,13,1000,9,1,9999
930410,868388,37.041550,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,592.664803,0.000000,...,9,1,3,3,1,13,22000,5,10,9999
930411,397491,37.041550,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,592.664803,0.000000,...,9,1,7,7,1,13,120000,3,5,9999
930412,892877,37.041550,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,592.664803,0.000000,...,9,1,88,88,1,13,99999999,9,99,9999
930413,700253,37.019784,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9,1,2,2,3,13,99999999,9,1,9999
930414,177714,37.037277,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,592.596438,0.000000,...,9,1,5,5,1,13,99999999,2,3,4
930415,38332,37.037277,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,592.596438,0.000000,...,9,1,5,5,1,13,48000,2,3,9999
930416,700854,37.037277,0.000000,0.000000,0.000000,0.000000,0.000000,592.596438,0.000000,0.000000,...,9,1,7,7,6,13,130000,6,11,9999
930417,821443,37.037277,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,8,8,6,6,88,13,78000,6,11,9999
930418,116531,37.042280,0.000000,0.000000,592.676474,0.000000,0.000000,0.000000,0.000000,0.000000,...,9,1,6,6,5,13,81000,5,9,9999
930419,499993,37.037277,0.000000,0.000000,0.000000,592.596438,0.000000,0.000000,0.000000,0.000000,...,0,2,2,3,88,2,99999999,9,1,2
930420,339051,37.037277,0.000000,0.000000,0.000000,592.596438,0.000000,0.000000,0.000000,0.000000,...,0,2,1,0,88,2,99999999,6,12,9999

---

## Language Mapping

Mappings languages between the 2016 and 1991 datasets, and providing standardized language group names.

In [29]:
language_mappings = pd.read_csv('Language_Mappings.csv')

language_mappings

,HLANO_2016_ID,HLANO_(Home_Language),MTNNO_2016_ID,MTNNO_(Mother_Tongue),HLNP_1991_ID,HLNP_(Home_Language),MTNP_1991_ID,MTNP_(Mother_Tongue),Equivalency_Class
0,NaN,NaN,NaN,NaN,3.0,English and French,3.0,English and French,Official_Languages
1,NaN,NaN,NaN,NaN,1.0,English single response,1.0,English single response,Official_Languages
2,NaN,NaN,NaN,NaN,2.0,French single response,2.0,French single response,Official_Languages
3,2.0,Aboriginal languages,2.0,Aboriginal languages,4.0,NOL: Aboriginal languages,4.0,NOL: Aboriginal languages,Aboriginal
4,24.0,All other languages,32.0,All other single languages,15.0,NOL: Other,18.0,NOL: Other,All_Other_Languages
5,NaN,NaN,NaN,NaN,16.0,NOL: Other (Atl./Terr. only),19.0,NOL: Other (Atl./Terr. only),All_Other_Languages
6,11.0,Arabic,3.0,Arabic,12.0,NOL: Arabic,15.0,NOL: Arabic,Arabic
7,20.0,Austro-Asiatic languages,20.0,Austro-Asiatic languages,11.0,NOL: Austro-Asiatic languages,14.0,NOL: Austro-Asiatic languages,Austro-Asiatic Languages
8,17.0,Cantonese,5.0,Cantonese,NaN,NaN,NaN,NaN,Chinese_Languages
9,19.0,Chinese languages,6.0,Chinese languages,10.0,NOL: Chinese,13.0,NOL: Chinese,Chinese_Languages
10,6.0,German,7.0,German,5.0,NOL: German,5.0,NOL: German,German
11,NaN,NaN,9.0,Greek,NaN,NaN,12.0,NOL: Greek,All_Other_Languages
12,3.0,Italian,13.0,Italian,6.0,NOL: Italian,7.0,NOL: Italian,Italian
13,NaN,NaN,NaN,NaN,NaN,NaN,6.0,NOL: Netherlandic languages,All_Other_Languages
14,NaN,NaN,28.0,Korean,NaN,NaN,NaN,NaN,All_Other_Languages
15,18.0,Mandarin,4.0,Mandarin,NaN,NaN,NaN,NaN,Chinese_Languages
16,NaN,NaN,31.0,Niger-Congo languages and other African languages,NaN,NaN,NaN,NaN,All_Other_Languages
17,1.0,No non-official language,1.0,No non-official language,NaN,NaN,NaN,NaN,Official_Languages
18,88.0,Not available,88.0,Not available,98.0,Not available,98.0,Not available,Not_Available
19,12.0,Other Afro-Asiatic and African languages,25.0,Other Afro-Asiatic languages,NaN,NaN,NaN,NaN,All_Other_Languages
20,NaN,NaN,27.0,Other Dravidian languages,NaN,NaN,NaN,NaN,All_Other_Languages
21,22.0,Other East and Southeast Asian languages,29.0,Other East and Southeast Asian languages,NaN,NaN,NaN,NaN,All_Other_Languages
22,10.0,Other European languages,21.0,Other European languages,NaN,NaN,NaN,NaN,All_Other_Languages
23,NaN,NaN,8.0,Other Germanic languages,NaN,NaN,NaN,NaN,All_Other_Languages
24,16.0,Other Indo-Iranian languages,12.0,Other Indo-Iranian languages,14.0,NOL: Other Indo-Iran.,17.0,NOL: Other Indo-Iran.,Other_Indo_Iranian_Languages
25,9.0,Slavic languages,23.0,Other Slavic languages,NaN,NaN,NaN,NaN,All_Other_Languages
26,15.0,Persian (Farsi),11.0,Persian (Farsi),NaN,NaN,NaN,NaN,Other_Indo_Iranian_Languages
27,8.0,Polish,14.0,Polish,9.0,NOL: Polish,10.0,NOL: Polish,Polish
28,5.0,Portuguese,15.0,Portuguese,8.0,NOL: Portuguese,9.0,NOL: Portuguese,Portuguese
29,13.0,Punjabi (Panjabi),16.0,Punjabi (Panjabi),13.0,NOL: Punjabi,16.0,NOL: Punjabi,Punjabi
30,7.0,Russian,22.0,Russian,NaN,NaN,NaN,NaN,All_Other_Languages
31,4.0,Spanish,17.0,Spanish,7.0,NOL: Spanish,8.0,NOL: Spanish,Spanish
32,21.0,"Tagalog (Pilipino, Filipino)",30.0,"Tagalog (Pilipino, Filipino)",NaN,NaN,NaN,NaN,All_Other_Languages
33,23.0,Tamil,26.0,Tamil,NaN,NaN,NaN,NaN,All_Other_Languages
34,NaN,NaN,18.0,Ukrainian,NaN,NaN,11.0,NOL: Ukrainian,All_Other_Languages
35,NaN,NaN,24.0,Uralic languages,NaN,NaN,NaN,NaN,All_Other_Languages
36,14.0,Urdu,10.0,Urdu,NaN,NaN,NaN,NaN,Other_Indo_Iranian_Languages
37,NaN,NaN,19.0,Vietnamese,NaN,NaN,NaN,NaN,Austro-Asiatic Languages

In [36]:
from math import isnan

print(isnan(language_mappings['HLANO_2016_ID'][0]))
print(isnan(language_mappings['HLANO_2016_ID'][3]))

True
False

### Pipeline: Language Mapping

In [61]:
def get_language_mappings():
    """Get language mapping dicts, separated into subdicts by feature name."""

    hlano = {}
    mtnno = {}
    hlnp = {}
    mtnp = {}
    classes = set()

    for row in list(language_mappings.itertuples()):
        # print(row[1])
        # print(row[3])
        # print(row[5])
        # print(row[7])
        # print(row[9])

        classes.add(row[9])
        
        if not isnan(row[1]):
            hlano[int(row[1])] = row[9]
        if not isnan(row[3]):
            mtnno[int(row[3])] = row[9]
        if not isnan(row[5]):
            hlnp[int(row[5])] = row[9]
        if not isnan(row[7]):
            mtnp[int(row[7])] = row[9]

    return {
        'hlano': hlano,
        'mtnno': mtnno,
        'hlnp': hlnp,
        'mtnp': mtnp,
        'classes': list(classes)
    }


get_language_mappings()

{'hlano': {2: 'Aboriginal',
  24: 'All_Other_Languages',
  11: 'Arabic',
  20: 'Austro-Asiatic Languages',
  17: 'Chinese_Languages',
  19: 'Chinese_Languages',
  6: 'German',
  3: 'Italian',
  18: 'Chinese_Languages',
  1: 'Official_Languages',
  88: 'Not_Available',
  12: 'All_Other_Languages',
  22: 'All_Other_Languages',
  10: 'All_Other_Languages',
  16: 'Other_Indo_Iranian_Languages',
  9: 'All_Other_Languages',
  15: 'Other_Indo_Iranian_Languages',
  8: 'Polish',
  5: 'Portuguese',
  13: 'Punjabi',
  7: 'All_Other_Languages',
  4: 'Spanish',
  21: 'All_Other_Languages',
  23: 'All_Other_Languages',
  14: 'Other_Indo_Iranian_Languages'},
 'mtnno': {2: 'Aboriginal',
  32: 'All_Other_Languages',
  3: 'Arabic',
  20: 'Austro-Asiatic Languages',
  5: 'Chinese_Languages',
  6: 'Chinese_Languages',
  7: 'German',
  9: 'All_Other_Languages',
  13: 'Italian',
  28: 'All_Other_Languages',
  4: 'Chinese_Languages',
  31: 'All_Other_Languages',
  1: 'Official_Languages',
  88: 'Not_Available',
  25: 'All_Other_Languages',
  27: 'All_Other_Languages',
  29: 'All_Other_Languages',
  21: 'All_Other_Languages',
  8: 'All_Other_Languages',
  12: 'Other_Indo_Iranian_Languages',
  23: 'All_Other_Languages',
  11: 'Other_Indo_Iranian_Languages',
  14: 'Polish',
  15: 'Portuguese',
  16: 'Punjabi',
  22: 'All_Other_Languages',
  17: 'Spanish',
  30: 'All_Other_Languages',
  26: 'All_Other_Languages',
  18: 'All_Other_Languages',
  24: 'All_Other_Languages',
  10: 'Other_Indo_Iranian_Languages',
  19: 'Austro-Asiatic Languages'},
 'hlnp': {3: 'Official_Languages',
  1: 'Official_Languages',
  2: 'Official_Languages',
  4: 'Aboriginal',
  15: 'All_Other_Languages',
  16: 'All_Other_Languages',
  12: 'Arabic',
  11: 'Austro-Asiatic Languages',
  10: 'Chinese_Languages',
  5: 'German',
  6: 'Italian',
  98: 'Not_Available',
  14: 'Other_Indo_Iranian_Languages',
  9: 'Polish',
  8: 'Portuguese',
  13: 'Punjabi',
  7: 'Spanish'},
 'mtnp': {3: 'Official_Languages',
  1: 'Official_Languages',
  2: 'Official_Languages',
  4: 'Aboriginal',
  18: 'All_Other_Languages',
  19: 'All_Other_Languages',
  15: 'Arabic',
  14: 'Austro-Asiatic Languages',
  13: 'Chinese_Languages',
  5: 'German',
  12: 'All_Other_Languages',
  7: 'Italian',
  6: 'All_Other_Languages',
  98: 'Not_Available',
  17: 'Other_Indo_Iranian_Languages',
  10: 'Polish',
  9: 'Portuguese',
  16: 'Punjabi',
  8: 'Spanish',
  11: 'All_Other_Languages'},
 'classes': ['Polish',
  'German',
  'Official_Languages',
  'Punjabi',
  'Austro-Asiatic Languages',
  'Portuguese',
  'Italian',
  'Spanish',
  'Other_Indo_Iranian_Languages',
  'Chinese_Languages',
  'All_Other_Languages',
  'Arabic',
  'Not_Available',
  'Aboriginal']}