In [1]:
import pandas as pd
dataset = pd.read_csv("pumf-98M0001-E-2016-individuals_F1.csv")
dataset.head()

,PPSORT,WEIGHT,WT1,WT2,WT3,WT4,WT5,WT6,WT7,WT8,...,Subsidy,Tenur,TotInc,TotInc_AT,VALUE,VisMin,Wages,WKSWRK,WRKACT,YRIMM
0,453141,37.037277,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,9,1,97000,73000,450000,13,95000,6,11,9999
1,923226,37.037277,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,9,1,99999999,99999999,440000,13,99999999,9,99,9999
2,385097,37.037277,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,9,1,99999999,99999999,440000,13,99999999,9,99,9999
3,732612,37.037277,0.0,0.0,0.0,0.0,0.0,0.0,0.0,592.596438,...,9,1,46000,41000,839779,13,19000,6,11,9999
4,143665,37.120914,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,9,1,30000,26000,60000,13,29000,5,9,9999

In [52]:
# class label: home language part A - first language write in component
homeLang = dataset.iloc[:,65]
# class label: mother tongue part A - first language write in component
motherTongue = dataset.iloc[:, 96]
# variables
x1, x2, x3 = dataset.iloc[:, 18:65], dataset.iloc[:, 66:96], dataset.iloc[:, 97:-1]
x = pd.concat([x1,x2,x3], axis=1, sort=False)
weights = dataset.iloc[:, 1]

In [29]:
homeLang

0          1
1          1
2          1
3          1
4          1
5          1
6          1
7          1
8          1
9          1
10         1
11         1
12         1
13         1
14         1
15         1
16         1
17         1
18         1
19         1
20         1
21         1
22         1
23         1
24         1
25         1
26         1
27         1
28         1
29         1
          ..
930391     1
930392     1
930393     1
930394     1
930395     1
930396     1
930397    23
930398     1
930399     1
930400     1
930401     1
930402     1
930403     1
930404     1
930405     1
930406     1
930407     1
930408     1
930409     1
930410     1
930411     1
930412     1
930413     1
930414     1
930415     1
930416     1
930417     1
930418     1
930419    17
930420     1
Name: HLANO, Length: 930421, dtype: int64

In [31]:
motherTongue

0          1
1          1
2          1
3          1
4          1
5          1
6          1
7          1
8          1
9          1
10         1
11         1
12         1
13         1
14         1
15         1
16         1
17         1
18         1
19         5
20         1
21         4
22         1
23         1
24         1
25         1
26         1
27         1
28         1
29         1
          ..
930391     1
930392     1
930393     1
930394     1
930395     1
930396    17
930397    26
930398    13
930399     1
930400     1
930401     1
930402     1
930403     1
930404     1
930405     1
930406     1
930407    30
930408     1
930409     1
930410     1
930411     1
930412     1
930413     1
930414     1
930415     1
930416     1
930417     1
930418     1
930419     5
930420     1
Name: MTNNO, Length: 930421, dtype: int64

In [53]:
x

,ABOID,AGEGRP,AGEIMM,ATTSCH,BedRm,BFNMEMB,CapGn,CFInc,CFInc_AT,CfSize,...,SSGRAD,Subsidy,Tenur,TotInc,TotInc_AT,VALUE,VisMin,Wages,WKSWRK,WRKACT
0,6,11,99,1,5,0,99999999,30,27,4,...,5,9,1,97000,73000,450000,13,95000,6,11
1,6,5,99,9,5,0,99999999,30,27,4,...,99,9,1,99999999,99999999,440000,13,99999999,9,99
2,6,2,99,9,5,0,99999999,30,27,4,...,99,9,1,99999999,99999999,440000,13,99999999,9,99
3,6,12,99,1,4,0,99999999,20,19,4,...,8,9,1,46000,41000,839779,13,19000,6,11
4,6,15,99,1,2,0,99999999,16,15,2,...,6,9,1,30000,26000,60000,13,29000,5,9
5,6,19,99,1,3,0,-3300,28,26,2,...,4,9,1,82000,69000,839779,13,99999999,9,1
6,6,18,99,1,3,0,-3400,28,26,2,...,6,9,1,51000,45000,839779,13,99999999,9,1
7,6,18,99,1,3,0,99999999,13,12,1,...,6,9,1,41000,37000,310000,13,99999999,9,1
8,6,14,99,1,2,0,99999999,25,21,2,...,5,0,2,53000,43000,99999999,13,52000,6,11
9,6,8,99,4,4,0,99999999,33,31,4,...,4,9,1,27000,26000,640000,13,27000,4,7
10,6,11,99,1,4,0,99999999,17,15,4,...,4,0,2,43000,31000,99999999,13,57000,6,11
11,6,1,99,9,4,0,99999999,17,15,4,...,99,0,2,99999999,99999999,99999999,13,99999999,9,99
12,1,16,99,1,2,0,99999999,6,6,1,...,1,0,2,14000,14000,99999999,13,99999999,9,1
13,6,11,99,3,3,0,99999999,30,27,3,...,8,9,1,72000,60000,600000,13,70000,6,11
14,6,11,99,1,3,0,99999999,28,26,4,...,4,9,1,58000,53000,340000,13,55000,6,11
15,6,4,99,9,3,0,99999999,28,26,4,...,99,9,1,99999999,99999999,340000,13,99999999,9,99
16,6,12,99,1,3,0,99999999,23,20,4,...,6,9,1,6000,6000,280000,13,99999999,6,11
17,6,8,99,1,3,0,99999999,25,24,4,...,4,9,1,24000,22000,280000,13,24000,6,11
18,6,15,99,1,2,0,99999999,13,12,1,...,4,0,2,42000,37000,99999999,13,11000,1,4
19,6,11,2,1,3,0,1400,28,25,4,...,8,9,1,120000,98000,550000,12,120000,6,11
20,6,1,99,9,3,0,99999999,28,25,4,...,99,9,1,99999999,99999999,560000,12,99999999,9,99
21,6,12,99,1,4,0,99999999,29,25,4,...,8,9,1,2000,2000,710000,2,99999999,9,1
22,6,19,99,1,3,0,99999999,12,12,2,...,1,9,1,29000,28000,60000,13,1000,9,1
23,6,6,99,2,4,0,99999999,33,31,3,...,1,9,1,99999999,99999999,859257,13,99999999,9,1
24,6,9,99,1,3,0,99999999,14,12,1,...,6,0,2,47000,38000,99999999,13,47000,6,11
25,6,14,99,1,4,0,99999999,15,13,1,...,4,9,1,52000,43000,270000,13,60000,5,9
26,6,1,99,9,5,0,99999999,25,22,4,...,99,9,1,99999999,99999999,1310000,1,99999999,9,99
27,6,8,99,1,5,0,99999999,10,9,1,...,4,9,1,28000,25000,1300000,13,26000,6,11
28,6,1,99,9,4,0,99999999,29,26,4,...,99,9,1,99999999,99999999,956142,12,99999999,9,99
29,6,6,99,2,4,0,99999999,25,22,4,...,1,9,1,99999999,99999999,790000,13,99999999,6,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
930391,6,12,99,1,4,0,99999999,31,29,4,...,8,9,1,63000,53000,240000,13,67000,6,11
930392,6,12,99,1,4,0,99999999,88,88,4,...,8,9,1,88888888,88888888,230000,13,88888888,6,11
930393,6,10,99,1,3,0,99999999,24,22,4,...,5,9,1,50000,40000,180000,13,50000,6,11
930394,6,3,99,9,3,0,99999999,24,22,4,...,99,9,1,99999999,99999999,180000,13,99999999,9,99
930395,6,2,99,9,3,0,99999999,24,22,4,...,99,9,1,99999999,99999999,180000,13,99999999,9,99
930396,6,1,99,9,2,0,99999999,9,9,3,...,99,0,2,99999999,99999999,99999999,13,99999999,9,99
930397,6,2,99,9,3,0,99999999,14,13,3,...,99,9,1,99999999,99999999,600000,13,99999999,9,99
930398,6,19,6,1,3,0,1600,31,27,1,...,11,9,1,418101,251438,900000,13,99999999,9,1
930399,6,12,99,1,4,0,-100,28,25,5,...,7,9,1,140000,100000,370000,13,130000,6,11
930400,6,5,99,9,4,0,99999999,28,25,5,...,99,9,1,99999999,99999999,360000,13,99999999,9,99
930401,6,5,99,9,4,0,99999999,28,25,5,...,99,9,1,99999999,99999999,350000,13,99999999,9,99
930402,6,4,99,9,4,0,99999999,28,25,5,...,99,9,1,99999999,99999999,350000,13,99999999,9,99
930403,1,10,99,1,3,1,99999999,8,8,3,...,2,1,2,1000,1,99999999,13,99999999,9,1
930404,6,17,99,1,1,0,99999999,15,13,1,...,1,0,2,52000,41000,99999999,13,17000,5,10
930405,6,11,99,1,2,0,99999999,16,16,1,...,4,0,2,59000,57000,99999999,13,99999999,5,9
930406,6,1,99,9,3,0,99999999,30,27,4,...,99,9,1,99999999,99999999,460000,13,99999999,9,99
930407,6,14,8,1,3,0,99999999,25,21,3,...,8,9,1,64000,49000,390000,4,64000,6,11
930408,6,18,99,1,1,0,99999999,12,12,1,...,6,0,2,37000,36000,99999999,13,28000,5,9
930409,6,21,99,1,2,0,99999999,16,15,2,...,9,9,1,48000,47000,190000,13,1000,9,1
930410,6,11,99,1,4,0,99999999,30,25,4,...,5,9,1,26000,24000,230000,13,22000,5,10
930411,6,11,99,1,4,0,99999999,30,25,4,...,5,9,1,130000,83000,240000,13,120000,3,5
930412,6,3,99,9,4,0,99999999,30,25,4,...,99,9,1,99999999,99999999,250000,13,99999999,9,99
930413,6,10,99,1,5,0,99999999,11,11,2,...,4,9,1,18000,17000,380000,13,99999999,9,1
930414,6,15,2,1,3,0,99999999,24,21,2,...,4,9,1,48000,42000,200000,13,99999999,2,3
930415,6,14,99,1,3,0,99999999,24,21,2,...,4,9,1,49000,42000,200000,13,48000,2,3
930416,6,17,99,1,4,0,200,31,28,2,...,8,9,1,120000,94000,810000,13,130000,6,11
930417,6,13,99,1,8,0,99999999,30,27,4,...,2,8,8,77000,61000,88888888,13,78000,6,11
930418,6,13,99,1,3,0,99999999,21,17,1,...,6,9,1,80000,62000,710000,13,81000,5,9
930419,6,21,7,1,3,0,99999999,13,13,3,...,1,0,2,22000,23000,99999999,2,99999999,9,1
930420,6,14,99,1,3,0,99999999,13,13,3,...,6,0,2,9000,8000,99999999,2,99999999,6,12

In [33]:
weights

0         37.037277
1         37.037277
2         37.037277
3         37.037277
4         37.120914
5         37.037277
6         37.037277
7         37.019784
8         37.041550
9         37.037277
10        37.037277
11        37.037277
12        37.039118
13        37.037277
14        37.039118
15        37.039118
16        37.037277
17        37.037277
18        37.042280
19        37.042280
20        37.042280
21        37.037277
22        37.039118
23        37.037277
24        37.012589
25        37.041550
26        37.042280
27        37.042280
28        37.041550
29        37.042280
            ...
930391    37.040742
930392    37.040742
930393    37.041550
930394    37.041550
930395    37.041550
930396    37.041550
930397    37.037277
930398    37.037277
930399    37.051222
930400    37.051222
930401    37.051222
930402    37.051222
930403    37.019784
930404    37.032779
930405    37.019784
930406    37.037277
930407    37.041550
930408    37.037277
930409    37.032779
930410    37.041550
930411    37.041550
930412    37.041550
930413    37.019784
930414    37.037277
930415    37.037277
930416    37.037277
930417    37.037277
930418    37.042280
930419    37.037277
930420    37.037277
Name: WEIGHT, Length: 930421, dtype: float64

In [38]:
from sklearn.ensemble import RandomForestClassifier

In [56]:
classifier = RandomForestClassifier(n_estimators=20, random_state=0)

In [54]:
from sklearn.model_selection import train_test_split
weights_train, weights_test, x_train, x_test, homeLang_train, homeLang_test, motherTongue_train, motherTongue_test = train_test_split(weights, x, homeLang, motherTongue)

In [57]:
classifier.fit(x_train, homeLang_train, weights_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=20, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [58]:
homeLang_pred = classifier.predict(x_test)

In [66]:
langs=['No non-official language','Aboriginal languages','Italian','Spanish','Portuguese','German','Russian','Polish','Slavic languages','Other European languages','Arabic','Other Afro-Asiatic and African languages','Punjabi (Panjabi)','Urdu','Persian (Farsi)','Other Indo-Iranian languages','Cantonese','Mandarin','Chinese languages','Austro-Asiatic languages','Tagalog (Pilipino, Filipino)','Other East and Southeast Asian languages','Tamil','All other languages','Not available']

In [71]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

The Confusion Matrix indicates, given the predicted language (row names), for how many records did the algorith match the actual language. The classification report and accuracy score are other ways to evaluate how well the classification algorithm performed.

In [77]:
confusionMatrixHomeLang = pd.DataFrame(
    confusion_matrix(homeLang_test,homeLang_pred), 
    index=langs, 
    columns=langs
)

In [79]:
print(confusionMatrixHomeLang)
print(classification_report(homeLang_test,homeLang_pred,target_names=langs))
print(accuracy_score(homeLang_test, homeLang_pred))

                                          No non-official language  \
No non-official language                                    192011
Aboriginal languages                                           125
Italian                                                        294
Spanish                                                        408
Portuguese                                                     181
German                                                         287
Russian                                                        151
Polish                                                         153
Slavic languages                                               231
Other European languages                                       358
Arabic                                                         304
Other Afro-Asiatic and African languages                       290
Punjabi (Panjabi)                                              239
Urdu                                                           170
Persian (Farsi)                                                111
Other Indo-Iranian languages                                   391
Cantonese                                                      315
Mandarin                                                       211
Chinese languages                                               60
Austro-Asiatic languages                                        93
Tagalog (Pilipino, Filipino)                                   194
Other East and Southeast Asian languages                       159
Tamil                                                           83
All other languages                                            366
Not available                                                   97

                                          Aboriginal languages  Italian  \
No non-official language                                     4       27
Aboriginal languages                                       779        0
Italian                                                      0      733
Spanish                                                      0        2
Portuguese                                                   0        4
German                                                       0        3
Russian                                                      0        1
Polish                                                       0        3
Slavic languages                                             1        5
Other European languages                                     1        7
Arabic                                                       0        1
Other Afro-Asiatic and African languages                     0        0
Punjabi (Panjabi)                                            0        0
Urdu                                                         0        0
Persian (Farsi)                                              0        0
Other Indo-Iranian languages                                 0        0
Cantonese                                                    0        0
Mandarin                                                     0        0
Chinese languages                                            0        0
Austro-Asiatic languages                                     0        0
Tagalog (Pilipino, Filipino)                                 0        0
Other East and Southeast Asian languages                     0        0
Tamil                                                        0        0
All other languages                                          1        0
Not available                                                2        0

                                          Spanish  Portuguese  German  \
No non-official language                       85          12       9
Aboriginal languages                            0           0       0
Italian                                         5           4       1
Spanish                                      1929           5       3
Portuguese                                     78         552       2
German                                          5           2     482
Russian                                         7           2       8
Polish                                          6           4       3
Slavic languages                               12           2       3
Other European languages                       10           3      26
Arabic                                          0           0       0
Other Afro-Asiatic and African languages        1           0       2
Punjabi (Panjabi)                               4           0       1
Urdu                                            7           0       0
Persian (Farsi)                                10           0       0
Other Indo-Iranian languages                    6           0       1
Cantonese                                       7           0       0
Mandarin                                        1           0       1
Chinese languages                               0           0       0
Austro-Asiatic languages                        9           0       0
Tagalog (Pilipino, Filipino)                    0           1       0
Other East and Southeast Asian languages       11           0       1
Tamil                                           3           0       0
All other languages                            12           1       0
Not available                                  16           2       2

                                          Russian  Polish  Slavic languages  \
No non-official language                       11      16                11
Aboriginal languages                            0       1                 0
Italian                                         0       1                 7
Spanish                                         8       0                15
Portuguese                                      0       3                 8
German                                          6       1                 5
Russian                                       592       0                46
Polish                                          7     457                 7
Slavic languages                              106       6               581
Other European languages                       69      11                53
Arabic                                          2       1                 0
Other Afro-Asiatic and African languages       21       0                10
Punjabi (Panjabi)                               0       0                 1
Urdu                                            1       0                 0
Persian (Farsi)                                 2       0                 1
Other Indo-Iranian languages                    1       0                 0
Cantonese                                       0       0                 0
Mandarin                                        0       0                 0
Chinese languages                               0       0                 0
Austro-Asiatic languages                        0       0                 1
Tagalog (Pilipino, Filipino)                    0       0                 0
Other East and Southeast Asian languages        2       0                 0
Tamil                                           0       0                 0
All other languages                            12       0                60
Not available                                   1       7                11

                                          Other European languages  ...  \
No non-official language                                        13  ...
Aboriginal languages                                             0  ...
Italian                                                         14  ...
Spanish                                                          6  ...
Portuguese                                                       4  ...
German                                                          21  ...
Russian                                                         35  ...
Polish                                                          12  ...
Slavic languages                                                49  ...
Other European languages                                       784  ...
Arabic                                                           1  ...
Other Afro-Asiatic and African languages                         4  ...
Punjabi (Panjabi)                                                0  ...
Urdu                                                             1  ...
Persian (Farsi)                                                  1  ...
Other Indo-Iranian languages                                     0  ...
Cantonese                                                        1  ...
Mandarin                                                         0  ...
Chinese languages                                                0  ...
Austro-Asiatic languages                                         0  ...
Tagalog (Pilipino, Filipino)                                     0  ...
Other East and Southeast Asian languages                         0  ...
Tamil                                                            0  ...
All other languages                                              7  ...
Not available                                                    3  ...

                                          Other Indo-Iranian languages  \
No non-official language                                            82
Aboriginal languages                                                 0
Italian                                                              0
Spanish                                                              4
Portuguese                                                           4
German                                                               3
Russian                                                              1
Polish                                                               1
Slavic languages                                                     0
Other European languages                                             2
Arabic                                                               6
Other Afro-Asiatic and African languages                             3
Punjabi (Panjabi)                                                  121
Urdu                                                               146
Persian (Farsi)                                                     23
Other Indo-Iranian languages                                      1297
Cantonese                                                            2
Mandarin                                                             3
Chinese languages                                                    2
Austro-Asiatic languages                                             1
Tagalog (Pilipino, Filipino)                                         0
Other East and Southeast Asian languages                            13
Tamil                                                               87
All other languages                                                112
Not available                                                       27

                                          Cantonese  Mandarin  \
No non-official language                         52        79
Aboriginal languages                              0         0
Italian                                           1         0
Spanish                                           7         1
Portuguese                                        1         0
German                                            2         0
Russian                                           0         0
Polish                                            0         0
Slavic languages                                  0         0
Other European languages                          1         0
Arabic                                            1         0
Other Afro-Asiatic and African languages          0         0
Punjabi (Panjabi)                                 2         0
Urdu                                              3         1
Persian (Farsi)                                   2         0
Other Indo-Iranian languages                      2         3
Cantonese                                      2313       484
Mandarin                                        439      2900
Chinese languages                               193       148
Austro-Asiatic languages                         21         1
Tagalog (Pilipino, Filipino)                      5         2
Other East and Southeast Asian languages         15        10
Tamil                                             1         0
All other languages                               3         1
Not available                                    12         4

                                          Chinese languages  \
No non-official language                                  0
Aboriginal languages                                      0
Italian                                                   0
Spanish                                                   0
Portuguese                                                0
German                                                    0
Russian                                                   0
Polish                                                    0
Slavic languages                                          0
Other European languages                                  0
Arabic                                                    0
Other Afro-Asiatic and African languages                  0
Punjabi (Panjabi)                                         0
Urdu                                                      0
Persian (Farsi)                                           0
Other Indo-Iranian languages                              0
Cantonese                                                 4
Mandarin                                                  0
Chinese languages                                        14
Austro-Asiatic languages                                  0
Tagalog (Pilipino, Filipino)                              0
Other East and Southeast Asian languages                  0
Tamil                                                     0
All other languages                                       0
Not available                                             0

                                          Austro-Asiatic languages  \
No non-official language                                        25
Aboriginal languages                                             0
Italian                                                          0
Spanish                                                          0
Portuguese                                                       0
German                                                           0
Russian                                                          1
Polish                                                           0
Slavic languages                                                 1
Other European languages                                         0
Arabic                                                           0
Other Afro-Asiatic and African languages                         0
Punjabi (Panjabi)                                                3
Urdu                                                             3
Persian (Farsi)                                                  0
Other Indo-Iranian languages                                     1
Cantonese                                                       31
Mandarin                                                         1
Chinese languages                                               10
Austro-Asiatic languages                                       734
Tagalog (Pilipino, Filipino)                                     5
Other East and Southeast Asian languages                        30
Tamil                                                            1
All other languages                                              2
Not available                                                    3

                                          Tagalog (Pilipino, Filipino)  \
No non-official language                                           222
Aboriginal languages                                                 0
Italian                                                              0
Spanish                                                              1
Portuguese                                                           0
German                                                               0
Russian                                                              0
Polish                                                               0
Slavic languages                                                     0
Other European languages                                             1
Arabic                                                               0
Other Afro-Asiatic and African languages                             0
Punjabi (Panjabi)                                                    0
Urdu                                                                 1
Persian (Farsi)                                                      1
Other Indo-Iranian languages                                         0
Cantonese                                                            1
Mandarin                                                             2
Chinese languages                                                    2
Austro-Asiatic languages                                             3
Tagalog (Pilipino, Filipino)                                      2471
Other East and Southeast Asian languages                           181
Tamil                                                                0
All other languages                                                  2
Not available                                                       15

                                          Other East and Southeast Asian languages  \
No non-official language                                                        42
Aboriginal languages                                                             0
Italian                                                                          1
Spanish                                                                          4
Portuguese                                                                       3
German                                                                           0
Russian                                                                          3
Polish                                                                           1
Slavic languages                                                                 0
Other European languages                                                         0
Arabic                                                                           0
Other Afro-Asiatic and African languages                                         2
Punjabi (Panjabi)                                                                1
Urdu                                                                             3
Persian (Farsi)                                                                  2
Other Indo-Iranian languages                                                     2
Cantonese                                                                       10
Mandarin                                                                         6
Chinese languages                                                                4
Austro-Asiatic languages                                                         3
Tagalog (Pilipino, Filipino)                                                     7
Other East and Southeast Asian languages                                      1023
Tamil                                                                            1

                                          precision    recall  f1-score   support

                No non-official language       0.97      0.99      0.98    193099
                    Aboriginal languages       0.99      0.86      0.92       905
                                 Italian       0.93      0.69      0.79      1067
                                 Spanish       0.87      0.80      0.83      2406
                              Portuguese       0.94      0.65      0.77       844
                                  German       0.88      0.58      0.70       825
                                 Russian       0.70      0.67      0.69       884
                                  Polish       0.91      0.70      0.79       656
                        Slavic languages       0.71      0.58      0.64      1008
                Other European languages       0.82      0.59      0.68      1339
                                  Arabic       0.90      0.86      0.88      2471
Other Afro-Asiatic and African languages       0.83      0.63      0.71      1161
                       Punjabi (Panjabi)       0.81      0.87      0.84      3235
                                    Urdu       0.79      0.69      0.74      1366
                         Persian (Farsi)       0.82      0.83      0.82      1135
            Other Indo-Iranian languages       0.67      0.57      0.62      2264
                               Cantonese       0.75      0.73      0.74      3180
                                Mandarin       0.80      0.81      0.81      3569
                       Chinese languages       0.78      0.03      0.06       435
                Austro-Asiatic languages       0.86      0.84      0.85       871
            Tagalog (Pilipino, Filipino)       0.85      0.92      0.88      2686
Other East and Southeast Asian languages       0.91      0.70      0.79      1463
                                   Tamil       0.91      0.72      0.80       946
                     All other languages       0.81      0.41      0.54      1309
                           Not available       0.99      0.92      0.95      3482

                               micro avg       0.95      0.95      0.95    232606
                               macro avg       0.85      0.71      0.75    232606
                            weighted avg       0.95      0.95      0.95    232606

0.9527914155266846

In [86]:
!pip install tabulate

Requirement already satisfied: tabulate in c:\users\fogelm\anaconda3\lib\site-packages (0.8.6)

In [87]:
from tabulate import tabulate
importances = classifier.feature_importances_
headers = ["name", "score"]
values = sorted(zip(x_train.columns, classifier.feature_importances_), key=lambda x: x[1] * -1)
print(tabulate(values, headers, tablefmt="plain"))

name                    score
NOL               0.143366
POB               0.0576504
POBM              0.0548587
HLAEN             0.0476917
VisMin            0.0451349
AGEIMM            0.0411363
IMMCAT5           0.0375393
HLBNO             0.0366701
POBF              0.0353864
ETHDER            0.0319968
DPGRSUM           0.0307834
MTNEn             0.0176593
HLAFR             0.0123443
HLBEN             0.0121765
Citizen           0.0115869
CitOth            0.011024
FOL               0.00969152
CMA               0.00963925
SHELCO            0.0095124
AGEGRP            0.00904224
VALUE             0.00811551
HHMRKINC          0.00744955
GENSTAT           0.00742927
CFInc             0.00704207
EfDIMBM           0.00694523
ROOMS             0.00684971
PR1               0.00673065
TotInc            0.00663338
HHInc             0.00660585
CFInc_AT          0.00658781
SSGRAD            0.00651842
HHInc_AT          0.00649363
EFInc             0.00646597
EFInc_AT          0.00641379
LOCSTUD           0.00638574
TotInc_AT         0.00634685
PR                0.00631605
HDGREE            0.0062291
HHSIZE            0.00607058
KOL               0.00597631
PR5               0.00559875
GTRfs             0.00557104
EFDecile          0.00537409
EfSize            0.00533323
MrkInc            0.00519366
BedRm             0.00483207
CfSize            0.00476126
CIP2011_STEM_SUM  0.00451891
IMMSTAT           0.0043658
EmpIn             0.00432653
Mob5              0.00427715
MTNFr             0.00427429
GovtI             0.00423027
CIP2011           0.00418492
HHTYPE            0.00415663
NOC16             0.00412951
Wages             0.0040984
NAICS             0.0038917
IncTax            0.00383717
DETH123           0.00351853
LOC_ST_RES        0.00349184
PresMortG         0.00321929
DTYPE             0.00319508
CFSTAT            0.0031876
NOCS              0.00315313
NOS               0.00308558
WRKACT            0.00301475
Invst             0.00301394
MarStH            0.00280222
PWLEAVE           0.00279507
REPAIR            0.00271388
PWDUR             0.0025681
CQPPB             0.00251915
PWPR              0.0024903
LFACT             0.00248128
WKSWRK            0.00240756
POWST             0.00237032
DIST              0.0023448
ATTSCH            0.00225167
MOB1              0.00221531
Subsidy           0.00210487
OASGI             0.00206053
HCORENEED_IND     0.00201854
LSTWRK            0.00201795
CHDBN             0.00199254
Sex               0.00198013
PKID15_24         0.00195988
PKID6_14          0.00192601
PKID2_5           0.00188515
MODE              0.00178381
LWANO             0.00171639
PKID25            0.0016307
OtInc             0.00161006
PKID0_1           0.00160361
CONDO             0.00155518
SempI             0.00152717
Tenur             0.00145674
PWOCC             0.00144792
HLBFR             0.00131101
Retir             0.00129474
CapGn             0.0012822
LoMBM             0.00123516
LoLIMB            0.00120663
PKIDS             0.0012033
LWAEN             0.00118296
FPTWK             0.00116872
PRIHM             0.00115645
ABOID             0.00114315
COW               0.00113892
LWAFR             0.00112252
LWBNO             0.00109135
EICBN             0.00107569
ChldC             0.00105862
LICO              0.00105533
LoLIMA            0.00101922
LICO_AT           0.000854659
REGIND            0.000802398
BFNMEMB           0.00076493
LWBEN             0.000680672
LWBFR             0.000583756