In [2]:
import pandas as pd
dataset = pd.read_csv("pumf-98M0001-E-2016-individuals_F1.csv")
dataset.head()

,PPSORT,WEIGHT,WT1,WT2,WT3,WT4,WT5,WT6,WT7,WT8,...,Subsidy,Tenur,TotInc,TotInc_AT,VALUE,VisMin,Wages,WKSWRK,WRKACT,YRIMM
0,453141,37.037277,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,9,1,97000,73000,450000,13,95000,6,11,9999
1,923226,37.037277,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,9,1,99999999,99999999,440000,13,99999999,9,99,9999
2,385097,37.037277,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,9,1,99999999,99999999,440000,13,99999999,9,99,9999
3,732612,37.037277,0.0,0.0,0.0,0.0,0.0,0.0,0.0,592.596438,...,9,1,46000,41000,839779,13,19000,6,11,9999
4,143665,37.120914,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,9,1,30000,26000,60000,13,29000,5,9,9999

In [3]:
# class label: home language part A - first language write in component
homeLang = dataset.iloc[:,65]
# class label: mother tongue part A - first language write in component
motherTongue = dataset.iloc[:, 96]
# variables
x1, x2, x3 = dataset.iloc[:, 18:65], dataset.iloc[:, 66:96], dataset.iloc[:, 97:-1]
x = pd.concat([x1,x2,x3], axis=1, sort=False)
weights = dataset.iloc[:, 1]

In [4]:
homeLang

0          1
1          1
2          1
3          1
4          1
5          1
6          1
7          1
8          1
9          1
10         1
11         1
12         1
13         1
14         1
15         1
16         1
17         1
18         1
19         1
20         1
21         1
22         1
23         1
24         1
25         1
26         1
27         1
28         1
29         1
          ..
930391     1
930392     1
930393     1
930394     1
930395     1
930396     1
930397    23
930398     1
930399     1
930400     1
930401     1
930402     1
930403     1
930404     1
930405     1
930406     1
930407     1
930408     1
930409     1
930410     1
930411     1
930412     1
930413     1
930414     1
930415     1
930416     1
930417     1
930418     1
930419    17
930420     1
Name: HLANO, Length: 930421, dtype: int64

In [5]:
motherTongue

0          1
1          1
2          1
3          1
4          1
5          1
6          1
7          1
8          1
9          1
10         1
11         1
12         1
13         1
14         1
15         1
16         1
17         1
18         1
19         5
20         1
21         4
22         1
23         1
24         1
25         1
26         1
27         1
28         1
29         1
          ..
930391     1
930392     1
930393     1
930394     1
930395     1
930396    17
930397    26
930398    13
930399     1
930400     1
930401     1
930402     1
930403     1
930404     1
930405     1
930406     1
930407    30
930408     1
930409     1
930410     1
930411     1
930412     1
930413     1
930414     1
930415     1
930416     1
930417     1
930418     1
930419     5
930420     1
Name: MTNNO, Length: 930421, dtype: int64

In [6]:
x

,ABOID,AGEGRP,AGEIMM,ATTSCH,BedRm,BFNMEMB,CapGn,CFInc,CFInc_AT,CfSize,...,SSGRAD,Subsidy,Tenur,TotInc,TotInc_AT,VALUE,VisMin,Wages,WKSWRK,WRKACT
0,6,11,99,1,5,0,99999999,30,27,4,...,5,9,1,97000,73000,450000,13,95000,6,11
1,6,5,99,9,5,0,99999999,30,27,4,...,99,9,1,99999999,99999999,440000,13,99999999,9,99
2,6,2,99,9,5,0,99999999,30,27,4,...,99,9,1,99999999,99999999,440000,13,99999999,9,99
3,6,12,99,1,4,0,99999999,20,19,4,...,8,9,1,46000,41000,839779,13,19000,6,11
4,6,15,99,1,2,0,99999999,16,15,2,...,6,9,1,30000,26000,60000,13,29000,5,9
5,6,19,99,1,3,0,-3300,28,26,2,...,4,9,1,82000,69000,839779,13,99999999,9,1
6,6,18,99,1,3,0,-3400,28,26,2,...,6,9,1,51000,45000,839779,13,99999999,9,1
7,6,18,99,1,3,0,99999999,13,12,1,...,6,9,1,41000,37000,310000,13,99999999,9,1
8,6,14,99,1,2,0,99999999,25,21,2,...,5,0,2,53000,43000,99999999,13,52000,6,11
9,6,8,99,4,4,0,99999999,33,31,4,...,4,9,1,27000,26000,640000,13,27000,4,7
10,6,11,99,1,4,0,99999999,17,15,4,...,4,0,2,43000,31000,99999999,13,57000,6,11
11,6,1,99,9,4,0,99999999,17,15,4,...,99,0,2,99999999,99999999,99999999,13,99999999,9,99
12,1,16,99,1,2,0,99999999,6,6,1,...,1,0,2,14000,14000,99999999,13,99999999,9,1
13,6,11,99,3,3,0,99999999,30,27,3,...,8,9,1,72000,60000,600000,13,70000,6,11
14,6,11,99,1,3,0,99999999,28,26,4,...,4,9,1,58000,53000,340000,13,55000,6,11
15,6,4,99,9,3,0,99999999,28,26,4,...,99,9,1,99999999,99999999,340000,13,99999999,9,99
16,6,12,99,1,3,0,99999999,23,20,4,...,6,9,1,6000,6000,280000,13,99999999,6,11
17,6,8,99,1,3,0,99999999,25,24,4,...,4,9,1,24000,22000,280000,13,24000,6,11
18,6,15,99,1,2,0,99999999,13,12,1,...,4,0,2,42000,37000,99999999,13,11000,1,4
19,6,11,2,1,3,0,1400,28,25,4,...,8,9,1,120000,98000,550000,12,120000,6,11
20,6,1,99,9,3,0,99999999,28,25,4,...,99,9,1,99999999,99999999,560000,12,99999999,9,99
21,6,12,99,1,4,0,99999999,29,25,4,...,8,9,1,2000,2000,710000,2,99999999,9,1
22,6,19,99,1,3,0,99999999,12,12,2,...,1,9,1,29000,28000,60000,13,1000,9,1
23,6,6,99,2,4,0,99999999,33,31,3,...,1,9,1,99999999,99999999,859257,13,99999999,9,1
24,6,9,99,1,3,0,99999999,14,12,1,...,6,0,2,47000,38000,99999999,13,47000,6,11
25,6,14,99,1,4,0,99999999,15,13,1,...,4,9,1,52000,43000,270000,13,60000,5,9
26,6,1,99,9,5,0,99999999,25,22,4,...,99,9,1,99999999,99999999,1310000,1,99999999,9,99
27,6,8,99,1,5,0,99999999,10,9,1,...,4,9,1,28000,25000,1300000,13,26000,6,11
28,6,1,99,9,4,0,99999999,29,26,4,...,99,9,1,99999999,99999999,956142,12,99999999,9,99
29,6,6,99,2,4,0,99999999,25,22,4,...,1,9,1,99999999,99999999,790000,13,99999999,6,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
930391,6,12,99,1,4,0,99999999,31,29,4,...,8,9,1,63000,53000,240000,13,67000,6,11
930392,6,12,99,1,4,0,99999999,88,88,4,...,8,9,1,88888888,88888888,230000,13,88888888,6,11
930393,6,10,99,1,3,0,99999999,24,22,4,...,5,9,1,50000,40000,180000,13,50000,6,11
930394,6,3,99,9,3,0,99999999,24,22,4,...,99,9,1,99999999,99999999,180000,13,99999999,9,99
930395,6,2,99,9,3,0,99999999,24,22,4,...,99,9,1,99999999,99999999,180000,13,99999999,9,99
930396,6,1,99,9,2,0,99999999,9,9,3,...,99,0,2,99999999,99999999,99999999,13,99999999,9,99
930397,6,2,99,9,3,0,99999999,14,13,3,...,99,9,1,99999999,99999999,600000,13,99999999,9,99
930398,6,19,6,1,3,0,1600,31,27,1,...,11,9,1,418101,251438,900000,13,99999999,9,1
930399,6,12,99,1,4,0,-100,28,25,5,...,7,9,1,140000,100000,370000,13,130000,6,11
930400,6,5,99,9,4,0,99999999,28,25,5,...,99,9,1,99999999,99999999,360000,13,99999999,9,99
930401,6,5,99,9,4,0,99999999,28,25,5,...,99,9,1,99999999,99999999,350000,13,99999999,9,99
930402,6,4,99,9,4,0,99999999,28,25,5,...,99,9,1,99999999,99999999,350000,13,99999999,9,99
930403,1,10,99,1,3,1,99999999,8,8,3,...,2,1,2,1000,1,99999999,13,99999999,9,1
930404,6,17,99,1,1,0,99999999,15,13,1,...,1,0,2,52000,41000,99999999,13,17000,5,10
930405,6,11,99,1,2,0,99999999,16,16,1,...,4,0,2,59000,57000,99999999,13,99999999,5,9
930406,6,1,99,9,3,0,99999999,30,27,4,...,99,9,1,99999999,99999999,460000,13,99999999,9,99
930407,6,14,8,1,3,0,99999999,25,21,3,...,8,9,1,64000,49000,390000,4,64000,6,11
930408,6,18,99,1,1,0,99999999,12,12,1,...,6,0,2,37000,36000,99999999,13,28000,5,9
930409,6,21,99,1,2,0,99999999,16,15,2,...,9,9,1,48000,47000,190000,13,1000,9,1
930410,6,11,99,1,4,0,99999999,30,25,4,...,5,9,1,26000,24000,230000,13,22000,5,10
930411,6,11,99,1,4,0,99999999,30,25,4,...,5,9,1,130000,83000,240000,13,120000,3,5
930412,6,3,99,9,4,0,99999999,30,25,4,...,99,9,1,99999999,99999999,250000,13,99999999,9,99
930413,6,10,99,1,5,0,99999999,11,11,2,...,4,9,1,18000,17000,380000,13,99999999,9,1
930414,6,15,2,1,3,0,99999999,24,21,2,...,4,9,1,48000,42000,200000,13,99999999,2,3
930415,6,14,99,1,3,0,99999999,24,21,2,...,4,9,1,49000,42000,200000,13,48000,2,3
930416,6,17,99,1,4,0,200,31,28,2,...,8,9,1,120000,94000,810000,13,130000,6,11
930417,6,13,99,1,8,0,99999999,30,27,4,...,2,8,8,77000,61000,88888888,13,78000,6,11
930418,6,13,99,1,3,0,99999999,21,17,1,...,6,9,1,80000,62000,710000,13,81000,5,9
930419,6,21,7,1,3,0,99999999,13,13,3,...,1,0,2,22000,23000,99999999,2,99999999,9,1
930420,6,14,99,1,3,0,99999999,13,13,3,...,6,0,2,9000,8000,99999999,2,99999999,6,12

In [7]:
weights

0         37.037277
1         37.037277
2         37.037277
3         37.037277
4         37.120914
5         37.037277
6         37.037277
7         37.019784
8         37.041550
9         37.037277
10        37.037277
11        37.037277
12        37.039118
13        37.037277
14        37.039118
15        37.039118
16        37.037277
17        37.037277
18        37.042280
19        37.042280
20        37.042280
21        37.037277
22        37.039118
23        37.037277
24        37.012589
25        37.041550
26        37.042280
27        37.042280
28        37.041550
29        37.042280
            ...
930391    37.040742
930392    37.040742
930393    37.041550
930394    37.041550
930395    37.041550
930396    37.041550
930397    37.037277
930398    37.037277
930399    37.051222
930400    37.051222
930401    37.051222
930402    37.051222
930403    37.019784
930404    37.032779
930405    37.019784
930406    37.037277
930407    37.041550
930408    37.037277
930409    37.032779
930410    37.041550
930411    37.041550
930412    37.041550
930413    37.019784
930414    37.037277
930415    37.037277
930416    37.037277
930417    37.037277
930418    37.042280
930419    37.037277
930420    37.037277
Name: WEIGHT, Length: 930421, dtype: float64

In [8]:
from sklearn.ensemble import RandomForestClassifier

In [9]:
classifier = RandomForestClassifier(n_estimators=20, random_state=0)

In [10]:
from sklearn.model_selection import train_test_split
weights_train, weights_test, x_train, x_test, homeLang_train, homeLang_test, motherTongue_train, motherTongue_test = train_test_split(weights, x, homeLang, motherTongue)

In [11]:
classifier.fit(x_train, homeLang_train, weights_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=20, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [12]:
homeLang_pred = classifier.predict(x_test)

In [13]:
langs=['No non-official language','Aboriginal languages','Italian','Spanish','Portuguese','German','Russian','Polish','Slavic languages','Other European languages','Arabic','Other Afro-Asiatic and African languages','Punjabi (Panjabi)','Urdu','Persian (Farsi)','Other Indo-Iranian languages','Cantonese','Mandarin','Chinese languages','Austro-Asiatic languages','Tagalog (Pilipino, Filipino)','Other East and Southeast Asian languages','Tamil','All other languages','Not available']

In [14]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

The Confusion Matrix indicates, given the predicted language (row names), for how many records did the algorith match the actual language. The classification report and accuracy score are other ways to evaluate how well the classification algorithm performed.

In [15]:
confusionMatrixHomeLang = pd.DataFrame(
    confusion_matrix(homeLang_test,homeLang_pred), 
    index=langs, 
    columns=langs
)

In [16]:
print(confusionMatrixHomeLang)
print(classification_report(homeLang_test,homeLang_pred,target_names=langs))
print(accuracy_score(homeLang_test, homeLang_pred))

                                          No non-official language  \
No non-official language                                    192620
Aboriginal languages                                           101
Italian                                                        297
Spanish                                                        430
Portuguese                                                     172
German                                                         251
Russian                                                        133
Polish                                                         147
Slavic languages                                               268
Other European languages                                       352
Arabic                                                         341
Other Afro-Asiatic and African languages                       312
Punjabi (Panjabi)                                              231
Urdu                                                           182
Persian (Farsi)                                                116
Other Indo-Iranian languages                                   354
Cantonese                                                      285
Mandarin                                                       198
Chinese languages                                               52
Austro-Asiatic languages                                       122
Tagalog (Pilipino, Filipino)                                   239
Other East and Southeast Asian languages                       169
Tamil                                                           75
All other languages                                            345
Not available                                                   94

                                          Aboriginal languages  Italian  \
No non-official language                                     5       28
Aboriginal languages                                       794        0
Italian                                                      0      804
Spanish                                                      0        4
Portuguese                                                   0        4
German                                                       1        2
Russian                                                      0        1
Polish                                                       0        6
Slavic languages                                             0        8
Other European languages                                     0        7
Arabic                                                       0        0
Other Afro-Asiatic and African languages                     0        0
Punjabi (Panjabi)                                            0        0
Urdu                                                         0        1
Persian (Farsi)                                              0        0
Other Indo-Iranian languages                                 0        0
Cantonese                                                    0        0
Mandarin                                                     0        0
Chinese languages                                            0        0
Austro-Asiatic languages                                     0        0
Tagalog (Pilipino, Filipino)                                 0        0
Other East and Southeast Asian languages                     0        0
Tamil                                                        0        0
All other languages                                          3        0
Not available                                               11        0

                                          Spanish  Portuguese  German  \
No non-official language                       62          10       4
Aboriginal languages                            0           0       0
Italian                                         6           2       0
Spanish                                      1916           9       0
Portuguese                                     78         522       2
German                                         10           1     512
Russian                                         8           0       8
Polish                                          6           3       1
Slavic languages                               10           8       1
Other European languages                       15           5      40
Arabic                                          1           0       1
Other Afro-Asiatic and African languages        2           0       1
Punjabi (Panjabi)                               2           0       0
Urdu                                            5           0       0
Persian (Farsi)                                12           0       0
Other Indo-Iranian languages                   11           0       1
Cantonese                                       6           0       1
Mandarin                                        2           0       1
Chinese languages                               0           0       0
Austro-Asiatic languages                        7           0       0
Tagalog (Pilipino, Filipino)                    2           0       0
Other East and Southeast Asian languages        8           1       0
Tamil                                           0           0       0
All other languages                            12           1       5
Not available                                  15           2       1

                                          Russian  Polish  Slavic languages  \
No non-official language                        7      14                18
Aboriginal languages                            0       0                 0
Italian                                         0       3                 2
Spanish                                         7       0                11
Portuguese                                      2       2                 8
German                                          8       0                 3
Russian                                       566       2                67
Polish                                          7     487                 8
Slavic languages                              105       7               521
Other European languages                       73      11                58
Arabic                                          1       0                 1
Other Afro-Asiatic and African languages       18       0                11
Punjabi (Panjabi)                               0       0                 0
Urdu                                            0       0                 1
Persian (Farsi)                                 0       0                 0
Other Indo-Iranian languages                    1       0                 1
Cantonese                                       0       0                 1
Mandarin                                        0       0                 1
Chinese languages                               0       0                 0
Austro-Asiatic languages                        0       1                 0
Tagalog (Pilipino, Filipino)                    0       0                 1
Other East and Southeast Asian languages        1       0                 1
Tamil                                           0       0                 0
All other languages                            11       0                81
Not available                                   7       4                11

                                          Other European languages  ...  \
No non-official language                                        15  ...
Aboriginal languages                                             0  ...
Italian                                                         13  ...
Spanish                                                          8  ...
Portuguese                                                       7  ...
German                                                          23  ...
Russian                                                         46  ...
Polish                                                          12  ...
Slavic languages                                                43  ...
Other European languages                                       735  ...
Arabic                                                           1  ...
Other Afro-Asiatic and African languages                         2  ...
Punjabi (Panjabi)                                                0  ...
Urdu                                                             0  ...
Persian (Farsi)                                                  3  ...
Other Indo-Iranian languages                                     0  ...
Cantonese                                                        0  ...
Mandarin                                                         1  ...
Chinese languages                                                0  ...
Austro-Asiatic languages                                         0  ...
Tagalog (Pilipino, Filipino)                                     1  ...
Other East and Southeast Asian languages                         0  ...
Tamil                                                            0  ...
All other languages                                              4  ...
Not available                                                    5  ...

                                          Other Indo-Iranian languages  \
No non-official language                                            93
Aboriginal languages                                                 0
Italian                                                              2
Spanish                                                              4
Portuguese                                                           1
German                                                               3
Russian                                                              1
Polish                                                               3
Slavic languages                                                     1
Other European languages                                             3
Arabic                                                               3
Other Afro-Asiatic and African languages                             3
Punjabi (Panjabi)                                                  129
Urdu                                                               151
Persian (Farsi)                                                     23
Other Indo-Iranian languages                                      1385
Cantonese                                                            6
Mandarin                                                             9
Chinese languages                                                    1
Austro-Asiatic languages                                             0
Tagalog (Pilipino, Filipino)                                         3
Other East and Southeast Asian languages                             9
Tamil                                                               46
All other languages                                                110
Not available                                                       11

                                          Cantonese  Mandarin  \
No non-official language                         76        73
Aboriginal languages                              0         0
Italian                                           0         0
Spanish                                           8         1
Portuguese                                        1         0
German                                            2         0
Russian                                           0         1
Polish                                            1         0
Slavic languages                                  0         0
Other European languages                          0         0
Arabic                                            1         2
Other Afro-Asiatic and African languages          0         1
Punjabi (Panjabi)                                 2         0
Urdu                                              2         0
Persian (Farsi)                                   2         1
Other Indo-Iranian languages                      6         2
Cantonese                                      2330       403
Mandarin                                        480      2781
Chinese languages                               187       103
Austro-Asiatic languages                         31         2
Tagalog (Pilipino, Filipino)                      3         1
Other East and Southeast Asian languages         10         5
Tamil                                             1         0
All other languages                               4         2
Not available                                     8         8

                                          Chinese languages  \
No non-official language                                  0
Aboriginal languages                                      0
Italian                                                   0
Spanish                                                   0
Portuguese                                                0
German                                                    0
Russian                                                   0
Polish                                                    0
Slavic languages                                          0
Other European languages                                  0
Arabic                                                    0
Other Afro-Asiatic and African languages                  0
Punjabi (Panjabi)                                         0
Urdu                                                      0
Persian (Farsi)                                           0
Other Indo-Iranian languages                              0
Cantonese                                                 2
Mandarin                                                  3
Chinese languages                                        12
Austro-Asiatic languages                                  1
Tagalog (Pilipino, Filipino)                              0
Other East and Southeast Asian languages                  0
Tamil                                                     0
All other languages                                       0
Not available                                             0

                                          Austro-Asiatic languages  \
No non-official language                                        18
Aboriginal languages                                             0
Italian                                                          0
Spanish                                                          0
Portuguese                                                       0
German                                                           0
Russian                                                          0
Polish                                                           1
Slavic languages                                                 1
Other European languages                                         1
Arabic                                                           1
Other Afro-Asiatic and African languages                         0
Punjabi (Panjabi)                                                6
Urdu                                                             0
Persian (Farsi)                                                  0
Other Indo-Iranian languages                                     1
Cantonese                                                       33
Mandarin                                                         3
Chinese languages                                               12
Austro-Asiatic languages                                       710
Tagalog (Pilipino, Filipino)                                     3
Other East and Southeast Asian languages                        39
Tamil                                                            1
All other languages                                              2
Not available                                                    5

                                          Tagalog (Pilipino, Filipino)  \
No non-official language                                           199
Aboriginal languages                                                 0
Italian                                                              0
Spanish                                                              1
Portuguese                                                           0
German                                                               1
Russian                                                              0
Polish                                                               0
Slavic languages                                                     0
Other European languages                                             0
Arabic                                                               0
Other Afro-Asiatic and African languages                             0
Punjabi (Panjabi)                                                    1
Urdu                                                                 0
Persian (Farsi)                                                      0
Other Indo-Iranian languages                                         0
Cantonese                                                            1
Mandarin                                                             0
Chinese languages                                                    3
Austro-Asiatic languages                                             2
Tagalog (Pilipino, Filipino)                                      2444
Other East and Southeast Asian languages                           199
Tamil                                                                0
All other languages                                                  3
Not available                                                       11

                                          Other East and Southeast Asian languages  \
No non-official language                                                        25
Aboriginal languages                                                             0
Italian                                                                          0
Spanish                                                                          4
Portuguese                                                                       2
German                                                                           0
Russian                                                                          0
Polish                                                                           2
Slavic languages                                                                 1
Other European languages                                                         0
Arabic                                                                           0
Other Afro-Asiatic and African languages                                         0
Punjabi (Panjabi)                                                                2
Urdu                                                                             1
Persian (Farsi)                                                                  2
Other Indo-Iranian languages                                                     5
Cantonese                                                                        4
Mandarin                                                                         7
Chinese languages                                                                7
Austro-Asiatic languages                                                         2
Tagalog (Pilipino, Filipino)                                                     6
Other East and Southeast Asian languages                                       996
Tamil                                                                            1

                                          precision    recall  f1-score   support

                No non-official language       0.97      0.99      0.98    193677
                    Aboriginal languages       0.98      0.89      0.93       895
                                 Italian       0.93      0.71      0.81      1131
                                 Spanish       0.87      0.79      0.83      2421
                              Portuguese       0.93      0.64      0.76       810
                                  German       0.88      0.62      0.73       828
                                 Russian       0.70      0.65      0.67       865
                                  Polish       0.92      0.71      0.80       686
                        Slavic languages       0.65      0.53      0.58       986
                Other European languages       0.80      0.56      0.66      1313
                                  Arabic       0.88      0.84      0.86      2353
Other Afro-Asiatic and African languages       0.84      0.62      0.71      1182
                       Punjabi (Panjabi)       0.82      0.87      0.84      3153
                                    Urdu       0.79      0.67      0.73      1356
                         Persian (Farsi)       0.81      0.83      0.82      1184
            Other Indo-Iranian languages       0.69      0.62      0.65      2250
                               Cantonese       0.74      0.75      0.75      3087
                                Mandarin       0.82      0.80      0.81      3489
                       Chinese languages       0.67      0.03      0.06       380
                Austro-Asiatic languages       0.85      0.80      0.82       889
            Tagalog (Pilipino, Filipino)       0.85      0.90      0.88      2705
Other East and Southeast Asian languages       0.93      0.68      0.79      1455
                                   Tamil       0.91      0.74      0.82       868
                     All other languages       0.79      0.40      0.53      1268
                           Not available       0.98      0.92      0.95      3375

                               micro avg       0.95      0.95      0.95    232606
                               macro avg       0.84      0.70      0.75    232606
                            weighted avg       0.95      0.95      0.95    232606

0.95317403678323

In [17]:
!pip install tabulate

Requirement already satisfied: tabulate in c:\users\fogelm\anaconda3\lib\site-packages (0.8.6)

In [18]:
from tabulate import tabulate
importances = classifier.feature_importances_
headers = ["name", "score"]
values = sorted(zip(x_train.columns, classifier.feature_importances_), key=lambda x: x[1] * -1)
print(tabulate(values, headers, tablefmt="plain"))

name                    score
NOL               0.138096
POB               0.0626972
POBM              0.0552743
HLAEN             0.0483975
VisMin            0.0444657
IMMCAT5           0.0368475
AGEIMM            0.0367611
HLBNO             0.0362365
POBF              0.0351036
DPGRSUM           0.0338352
ETHDER            0.0320855
MTNEn             0.0207346
HLAFR             0.012947
HLBEN             0.0125195
Citizen           0.0121783
CitOth            0.0110969
FOL               0.0102983
CMA               0.00964501
SHELCO            0.0094968
AGEGRP            0.00926378
VALUE             0.00806637
HHMRKINC          0.00739441
CFInc_AT          0.00723143
ROOMS             0.00710871
KOL               0.0070707
PR                0.00697155
CFInc             0.00691014
HHInc             0.00686497
TotInc            0.00672566
EfDIMBM           0.00669238
HHInc_AT          0.00661268
LOCSTUD           0.00642322
EFInc             0.00636467
EFInc_AT          0.00625864
HDGREE            0.00619648
TotInc_AT         0.00614769
HHSIZE            0.00597117
GENSTAT           0.00587817
PR1               0.00586153
GTRfs             0.0056688
SSGRAD            0.00559076
EfSize            0.00538431
MrkInc            0.00535894
CfSize            0.00493417
PR5               0.00488908
EFDecile          0.00484094
BedRm             0.00479052
LOC_ST_RES        0.0046517
EmpIn             0.00459107
MTNFr             0.0044462
Mob5              0.00442534
CIP2011           0.00432562
CIP2011_STEM_SUM  0.00431536
NOC16             0.00423351
GovtI             0.00422976
HHTYPE            0.0040727
Wages             0.00405945
NAICS             0.00389221
IMMSTAT           0.00382267
IncTax            0.00366912
CFSTAT            0.00335626
DTYPE             0.00325056
Invst             0.00320389
NOCS              0.00318828
WRKACT            0.00301171
PresMortG         0.00297816
NOS               0.00283031
PWLEAVE           0.00278221
REPAIR            0.00265884
LFACT             0.00259283
MarStH            0.00256603
PWPR              0.00253622
PWDUR             0.00248692
DETH123           0.00245789
POWST             0.0024436
WKSWRK            0.00242846
DIST              0.00239681
CQPPB             0.00238318
ATTSCH            0.00225166
MOB1              0.00213489
Sex               0.00202891
PKID6_14          0.00201498
CHDBN             0.00199889
Subsidy           0.00196274
PKID2_5           0.00196009
OASGI             0.00193655
LSTWRK            0.00193182
MODE              0.00191704
PKID15_24         0.0019067
HCORENEED_IND     0.00186127
LWANO             0.00162832
Tenur             0.0015793
OtInc             0.00156944
SempI             0.00151665
LWAFR             0.00151168
CONDO             0.00150672
PKID25            0.00149447
PWOCC             0.00148749
PKID0_1           0.00142352
HLBFR             0.00135134
CapGn             0.00135133
Retir             0.00134542
COW               0.00126052
PKIDS             0.00118335
ChldC             0.00117342
LWBNO             0.00116809
LoLIMA            0.00116334
PRIHM             0.00115349
EICBN             0.00108094
LoLIMB            0.00107255
LWAEN             0.00106163
FPTWK             0.00103998
LoMBM             0.00101568
LICO              0.000953913
LICO_AT           0.000938203
ABOID             0.00083895
BFNMEMB           0.000762491
LWBEN             0.000760104
LWBFR             0.000673405
REGIND            0.000553279

In [20]:
from sklearn.tree import export_graphviz
estimator = classifier.estimators_[5]
# Creates dot file named randomForestTreeSample.dot
export_graphviz(estimator, 
                out_file='randomForestTreeSample.dot', 
                feature_names = list(x.columns),
                class_names = langs,
                rounded = True, proportion = False, 
                precision = 2, filled = True,
                max_depth=5)